<?php
/*
Plugin Name: Page Title, Description & Open Graph Updater
Plugin URI: https://www.google.com/
Description: Page Title, Description & Open Graph Updater
Version: 1.02
Author: DDigital Apps
Author URI: https://ddigitalapps.com
*/
class Dieno_Quick_Page_Edits_Plugin_Setting {
    /**
     * Bootstraps the class and hooks required actions & filters.
     *
     */
    public static function init() {
        require_once( dirname( __FILE__ ) . '/Classes/setting.php' );
        require_once( dirname( __FILE__ ) . '/Classes/dieno_quick_edits_functions.php' );
        add_action( 'admin_enqueue_scripts', __CLASS__ . '::dieno_quick_page_edits_admin_assets' );
        add_action( 'wp_head', __CLASS__ . '::dieno_generate_og_metatags');
    }

    public static function dieno_quick_page_edits_admin_assets() {
        wp_enqueue_media();
        wp_enqueue_style( 'dieno_plugin_style', plugins_url( 'assets/css/plugin_style.css', __FILE__ ), array(), '1.01', 'all' );
        wp_enqueue_style( 'dieno_bootstrap_min_style', plugins_url( 'assets/css/bootstrap.min.css', __FILE__ ), array(), '5.1.3', 'all' );
        wp_enqueue_style( 'dieno_dataTables_bootstrap_min_style', plugins_url( 'assets/css/jquery.dataTables.min.css', __FILE__ ), array(), '1.11.3', 'all' );
        wp_enqueue_script( 'dieno_jquery_bootstrap_script', plugins_url( 'assets/js/bootstrap.min.js', __FILE__ ), array(), '5.1.3', 'all' );
        wp_enqueue_script( 'dieno_jquery_dataTables_script', plugins_url( 'assets/js/jquery.dataTables.min.js', __FILE__ ), array(), '1.01', 'all' );
        wp_enqueue_script( 'dieno_fontawsome_script', plugins_url( 'assets/js/3f9cb9add8.js', __FILE__ ), array(), '1.01', 'all' );
        wp_enqueue_script( 'dieno_plugin_script', plugins_url( 'assets/js/quick_edit_script.js', __FILE__ ), array(), '1.01', 'all' );
        wp_localize_script( 'dieno_plugin_script', 'dieno_ajax_object',array( 'ajax_url' => admin_url( 'admin-ajax.php' ) ) );
	}
    function dieno_generate_og_metatags() {
        global $post;
        global $wp_query;
        $post_obj = $wp_query->get_queried_object();
        $pageid = $post_obj->ID;
        $website_name = get_bloginfo( 'name' );
        $pagetitle = get_the_title($pageid);
        $pageogtitle = get_post_meta($pageid,'dieno_page_og_title',true);
        $pageogdescription = get_post_meta($pageid,'dieno_page_og_description',true);
        $pageogimage = get_post_meta($pageid,'dieno_page_og_image',true);
        $pageogtitle = ($pageogtitle == '') ? $pagetitle : $pageogtitle;
        $pageogdescription = ($pageogdescription == '') ? $pagetitle : $pageogdescription;
        $pageogimage = ($pageogimage == '') ? $website_name : $pageogimage;
        $page_meta_description = get_post_meta($pageid,'dieno_page_og_description',true);
        $page_meta_description = ($page_meta_description == '') ? $pagetitle.' - '.$website_name : $page_meta_description;
        if ($post->post_type == "page") {
    ?>
        <!-- Open Graph Meta Tags generated by Dieno -->
        <meta name="description" content="<?php echo esc_html( $page_meta_description ); ?>" />
        <meta property="og:title" content="<?php echo esc_html( $pageogtitle ); ?>" />
        <meta property="og:description" content="<?php echo esc_html( $pageogdescription ); ?>" />
        <meta property="og:image" content="<?php echo esc_html( $pageogimage ); ?>" />
        <!-- //Open Graph Meta Tags generated by Dieno -->
    <?php    
        }
    }
}
Dieno_Quick_Page_Edits_Plugin_Setting::init();